In [1]:
pip install numpy==1.26.4 evidently==0.2.8 pandas

Requirement already satisfied: numpy==1.26.4 in c:\users\asus\appdata\roaming\python\python313\site-packages (1.26.4)
Requirement already satisfied: evidently==0.2.8 in e:\anaconda\lib\site-packages (0.2.8)
Requirement already satisfied: pandas in e:\anaconda\lib\site-packages (2.3.3)
Requirement already satisfied: plotly>=5.5.0 in e:\anaconda\lib\site-packages (from evidently==0.2.8) (5.24.1)
Requirement already satisfied: statsmodels>=0.12.2 in e:\anaconda\lib\site-packages (from evidently==0.2.8) (0.14.4)
Requirement already satisfied: scikit-learn>=0.24.0 in e:\anaconda\lib\site-packages (from evidently==0.2.8) (1.6.1)
Requirement already satisfied: nltk>=3.6.7 in e:\anaconda\lib\site-packages (from evidently==0.2.8) (3.9.1)
Requirement already satisfied: scipy>=1.5.4 in e:\anaconda\lib\site-packages (from evidently==0.2.8) (1.15.3)
Requirement already satisfied: requests>=2.19.0 in e:\anaconda\lib\site-packages (from evidently==0.2.8) (2.32.3)
Requirement already satisfied: PyYAML>=5.1 in e:\anaconda\lib\site-packages (from evidently==0.2.8) (6.0.3)
Collecting pydantic<2 (from evidently==0.2.8)
  Using cached pydantic-1.10.26-cp313-cp313-win_amd64.whl.metadata (156 kB)
Requirement already satisfied: typing-extensions>=4.2.0 in e:\anaconda\lib\site-packages (from pydantic<2->evidently==0.2.8) (4.15.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\asus\appdata\roaming\python\python313\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in e:\anaconda\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in e:\anaconda\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: click in e:\anaconda\lib\site-packages (from nltk>=3.6.7->evidently==0.2.8) (8.1.8)
Requirement already satisfied: joblib in e:\anaconda\lib\site-packages (from nltk>=3.6.7->evidently==0.2.8) (1.4.2)
Requirement already satisfied: regex>=2021.8.3 in e:\anaconda\lib\site-packages (from nltk>=3.6.7->evidently==0.2.8) (2024.11.6)
Requirement already satisfied: tqdm in e:\anaconda\lib\site-packages (from nltk>=3.6.7->evidently==0.2.8) (4.67.1)
Requirement already satisfied: tenacity>=6.2.0 in e:\anaconda\lib\site-packages (from plotly>=5.5.0->evidently==0.2.8) (9.0.0)
Requirement already satisfied: packaging in e:\anaconda\lib\site-packages (from plotly>=5.5.0->evidently==0.2.8) (24.2)
Requirement already satisfied: six>=1.5 in c:\users\asus\appdata\roaming\python\python313\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: charset-normalizer<4,>=2 in e:\anaconda\lib\site-packages (from requests>=2.19.0->evidently==0.2.8) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in e:\anaconda\lib\site-packages (from requests>=2.19.0->evidently==0.2.8) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in e:\anaconda\lib\site-packages (from requests>=2.19.0->evidently==0.2.8) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in e:\anaconda\lib\site-packages (from requests>=2.19.0->evidently==0.2.8) (2026.1.4)
Requirement already satisfied: threadpoolctl>=3.1.0 in e:\anaconda\lib\site-packages (from scikit-learn>=0.24.0->evidently==0.2.8) (3.5.0)
Requirement already satisfied: patsy>=0.5.6 in e:\anaconda\lib\site-packages (from statsmodels>=0.12.2->evidently==0.2.8) (1.0.1)
Requirement already satisfied: colorama in c:\users\asus\appdata\roaming\python\python313\site-packages (from click->nltk>=3.6.7->evidently==0.2.8) (0.4.6)
Using cached pydantic-1.10.26-cp313-cp313-win_amd64.whl (1.9 MB)
Installing collected packages: pydantic
  Attempting uninstall: pydantic
    Found existing installation: pydantic 2.12.5
    Uninstalling pydantic-2.12.5:
      Successfully uninstalled pydantic-2.12.5
Successfully installed pydantic-1.10.26
Note: you may need to restart the kernel to use updated packages.

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
fastapi-cloud-cli 0.14.1 requires pydantic[email]>=2.8.0; python_version == "3.13", but you have pydantic 1.10.26 which is incompatible.
langchain 1.2.10 requires pydantic<3.0.0,>=2.7.4, but you have pydantic 1.10.26 which is incompatible.
langchain-core 1.2.16 requires pydantic<3.0.0,>=2.7.4, but you have pydantic 1.10.26 which is incompatible.
langgraph 1.0.10 requires pydantic>=2.7.4, but you have pydantic 1.10.26 which is incompatible.
langsmith 0.7.6 requires pydantic<3,>=2, but you have pydantic 1.10.26 which is incompatible.
pydantic-settings 2.6.1 requires pydantic>=2.7.0, but you have pydantic 1.10.26 which is incompatible.
thinc 8.3.10 requires pydantic<3.0.0,>=2.0.0, but you have pydantic 1.10.26 which is incompatible.
unstructured-client 0.42.10 requires pydantic>=2.11.2, but you have pydantic 1.10.26 which is incompatible.
ydata-profiling 0.0.dev0 requires pydantic<3,>=2, but you have pydantic 1.10.26 which is incompatible.

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
import pandas as pd

from evidently.dashboard import Dashboard
from evidently.tabs import DataDriftTab, CatTargetDriftTab

from evidently.model_profile import Profile
from evidently.profile_sections import DataDriftProfileSection

e:\anaconda\Lib\site-packages\evidently\analyzers\__init__.py:3: UserWarning: analyzers are deprecated, use metrics instead
  warnings.warn("analyzers are deprecated, use metrics instead")
e:\anaconda\Lib\site-packages\evidently\dashboard\__init__.py:8: UserWarning: dashboards are deprecated, use metrics instead
  warnings.warn("dashboards are deprecated, use metrics instead")
e:\anaconda\Lib\site-packages\evidently\tabs\__init__.py:8: UserWarning: 'import evidently.tabs' is deprecated, use 'import evidently.dashboard.tabs'
  warnings.warn(
e:\anaconda\Lib\site-packages\evidently\model_profile\__init__.py:8: UserWarning: model profiles are deprecated, use metrics instead
  warnings.warn("model profiles are deprecated, use metrics instead")
e:\anaconda\Lib\site-packages\evidently\profile_sections\__init__.py:8: UserWarning: 'import evidently.profile_sections' is deprecated, use 'import evidently.model_profile.sections'
  warnings.warn(

In [3]:
import pandas as pd
import numpy as np

data_url = r"C:\Users\Asus\Documents\Projects\Bangladesh-Railway-Ticket-Demand-Prediction-System\notebook\data\bangladesh_railway_tickets.csv"
data_frame = pd.read_csv(data_url)

In [4]:
data_frame.head()

,Ticket No,Issue Date,Issue Time,Passenger Name,From,To,Train Name,Train No,Departure Time,Coach,Seat Number,Seats Booked,Fare,Payment Method,Journey Date
0,BR8478729720,4/25/2026,13:19:56,Rakib Hossain,Chattogram,Sylhet,Paharika Express,783.0,8:15 PM,Shovon,B19,3.0,900.0,Nagad,4/27/2026
1,BR7219153552,3/3/2026,2:38:16,Tanvir Hasan,Dhaka,Chattogram,Subarna Express,701.0,7:00 AM,Non-AC Berth,C18,2.0,2400.0,City Bank,3/4/2026
2,BR8520704729,6/6/2026,21:53:02,Rifat Islam,Chattogram,Sylhet,Chattala Express,781.0,7:00 AM,Shovon Chair,B6,4.0,1600.0,BRAC Bank,6/13/2026
3,BR8941235199,11/11/2026,2:53:22,Abdul Karim,Dhaka,Chattogram,Mohanagar Express,727.0,9:00 AM,Non-AC Berth,B8,5.0,6000.0,Islami Bank,11/13/2026
4,BR2320871590,7/20/2026,21:45:03,Sadia Afrin,Dhaka,Sylhet,Upaban Express,751.0,6:15 AM,Shovon,B2,1.0,300.0,BRAC Bank,7/26/2026

In [5]:
data_frame.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 15 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   Ticket No       99999 non-null   object
 1   Issue Date      100000 non-null  object
 2   Issue Time      99999 non-null   object
 3   Passenger Name  99999 non-null   object
 4   From            99999 non-null   object
 5   To              99999 non-null   object
 6   Train Name      99999 non-null   object
 7   Train No        99999 non-null   float64
 8   Departure Time  99999 non-null   object
 9   Coach           99999 non-null   object
 10  Seat Number     99999 non-null   object
 11  Seats Booked    99999 non-null   float64
 12  Fare            99999 non-null   float64
 13  Payment Method  99999 non-null   object
 14   Journey Date   100000 non-null  object
dtypes: float64(3), object(12)
memory usage: 11.4+ MB

In [6]:
data_frame.shape

(100000, 15)

In [7]:
data_frame[:200]

,Ticket No,Issue Date,Issue Time,Passenger Name,From,To,Train Name,Train No,Departure Time,Coach,Seat Number,Seats Booked,Fare,Payment Method,Journey Date
0,BR8478729720,4/25/2026,13:19:56,Rakib Hossain,Chattogram,Sylhet,Paharika Express,783.0,8:15 PM,Shovon,B19,3.0,900.0,Nagad,4/27/2026
1,BR7219153552,3/3/2026,2:38:16,Tanvir Hasan,Dhaka,Chattogram,Subarna Express,701.0,7:00 AM,Non-AC Berth,C18,2.0,2400.0,City Bank,3/4/2026
2,BR8520704729,6/6/2026,21:53:02,Rifat Islam,Chattogram,Sylhet,Chattala Express,781.0,7:00 AM,Shovon Chair,B6,4.0,1600.0,BRAC Bank,6/13/2026
3,BR8941235199,11/11/2026,2:53:22,Abdul Karim,Dhaka,Chattogram,Mohanagar Express,727.0,9:00 AM,Non-AC Berth,B8,5.0,6000.0,Islami Bank,11/13/2026
4,BR2320871590,7/20/2026,21:45:03,Sadia Afrin,Dhaka,Sylhet,Upaban Express,751.0,6:15 AM,Shovon,B2,1.0,300.0,BRAC Bank,7/26/2026
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,BR3307258233,8/15/2026,17:37:18,Samiul Islam,Dhaka,Khulna,Khulna Express,763.0,8:30 PM,AC Chair,C9,4.0,2200.0,BRAC Bank,8/19/2026
196,BR1626391577,12/23/2026,4:20:09,Md. Rahim Uddin,Dhaka,Sylhet,Upaban Express,751.0,6:15 AM,AC Berth,D11,4.0,7200.0,DBBL,12/28/2026
197,BR7982479857,11/29/2026,22:22:27,Imran Hossain,Dhaka,Khulna,Khulna Express,763.0,8:30 PM,Shovon,D7,4.0,1200.0,City Bank,12/2/2026
198,BR6349898527,11/20/2026,10:06:00,Md. Rahim Uddin,Dhaka,Chattogram,Subarna Express,701.0,7:00 AM,AC Chair,B5,2.0,1100.0,Islami Bank,11/23/2026
199,BR2129561511,6/27/2026,9:31:10,Farhana Akter,Dhaka,Sylhet,Upaban Express,751.0,6:15 AM,AC Berth,B18,2.0,3600.0,Bkash,6/29/2026

In [8]:
data_frame[200:]

,Ticket No,Issue Date,Issue Time,Passenger Name,From,To,Train Name,Train No,Departure Time,Coach,Seat Number,Seats Booked,Fare,Payment Method,Journey Date
200,BR8544508281,8/28/2026,14:37:36,Farhana Akter,Dhaka,Chattogram,Mohanagar Express,727.0,9:00 AM,AC Berth,A5,5.0,9000.0,Bkash,9/4/2026
201,BR3590904030,6/24/2026,18:51:54,Rifat Islam,Dhaka,Rajshahi,Dhumketu Express,723.0,6:45 PM,AC Berth,A7,4.0,7200.0,Rocket,6/27/2026
202,BR8088788508,7/30/2026,21:21:35,Abdul Karim,Dhaka,Rajshahi,Dhumketu Express,723.0,6:45 PM,Shovon Chair,D3,4.0,1600.0,Islami Bank,8/3/2026
203,BR7660122162,5/15/2026,15:44:35,Tania Sultana,Dhaka,Rajshahi,Dhumketu Express,723.0,6:45 PM,Non-AC Berth,C5,4.0,4800.0,BRAC Bank,5/20/2026
204,BR7145833977,1/8/2026,20:41:10,Imran Hossain,Dhaka,Sylhet,Paharika Express,755.0,9:00 AM,Non-AC Berth,D17,2.0,2400.0,DBBL,1/13/2026
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,BR9150063932,10/14/2026,1:23:52,Samiul Islam,Dhaka,Sylhet,Paharika Express,755.0,9:00 AM,AC Chair,C18,4.0,2200.0,City Bank,10/22/2026
99996,BR3213981433,4/10/2026,1:49:57,Sadia Afrin,Dhaka,Khulna,Sundarban Express,761.0,7:45 AM,Non-AC Berth,D11,2.0,2400.0,BRAC Bank,4/17/2026
99997,BR2423648315,12/4/2026,16:17:59,Rifat Islam,Chattogram,Sylhet,Chattala Express,781.0,7:00 AM,AC Berth,B13,3.0,5400.0,Bkash,12/12/2026
99998,BR4024369500,10/9/2026,16:55:15,Farhana Akter,Dhaka,Chattogram,Subarna Express,701.0,7:00 AM,AC Berth,B9,4.0,7200.0,BRAC Bank,10/13/2026
99999,NaN,11/13/2026,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11/17/2026

In [ ]:
house_data_drift_dashboard = Dashboard(tabs=[DataDriftTab()])
house_data_drift_dashboard.calculate(data_frame[:200], data_frame[200:])

e:\anaconda\Lib\site-packages\scipy\stats\_stats_py.py:7335: RuntimeWarning: divide by zero encountered in divide
  terms = (f_obs - f_exp)**2 / f_exp
e:\anaconda\Lib\site-packages\scipy\stats\_stats_py.py:7335: RuntimeWarning: divide by zero encountered in divide
  terms = (f_obs - f_exp)**2 / f_exp
e:\anaconda\Lib\site-packages\scipy\stats\_stats_py.py:7335: RuntimeWarning: divide by zero encountered in divide
  terms = (f_obs - f_exp)**2 / f_exp
e:\anaconda\Lib\site-packages\scipy\stats\_stats_py.py:7335: RuntimeWarning: divide by zero encountered in divide
  terms = (f_obs - f_exp)**2 / f_exp
e:\anaconda\Lib\site-packages\scipy\stats\_stats_py.py:7335: RuntimeWarning: divide by zero encountered in divide
  terms = (f_obs - f_exp)**2 / f_exp

In [ ]:
house_data_drift_dashboard.show()

In [10]:
house_data_drift_dashboard.save('housing_data_drift_no_mapping.html')

# jSON

In [14]:
house_data_drift_profile = Profile(sections=[DataDriftProfileSection()])

In [15]:
house_data_drift_profile.json()

'{"data_drift": null, "timestamp": "2026-04-03 00:11:03.562795"}'